services:
  db:
    image: "postgres:16"
    restart: always
    environment:
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_USER=shouvik
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  etl:
    build: .
    depends_on:
      - db
volumes:
  db_data: